IS-66 - Create the Virtual Classrooms program view
the-coding-school/the-cs pull request #72
Opened 2017-10-12 01:24 UTC by crayolakat

2017-10-18 17:18 UTC, bibekg commented
Glad to see progress! Make sure you change the base branch on this PR to `programs-page-redesign` since we want to aggregate these changes there first. 

Also, did you create this branch off of `master` or that branch?

2017-10-26 16:35 UTC, crayolakat commented
I created this branch off the programs-page-redesign branch

2017-10-28 02:21 UTC, bibekg commented
Okay cool, in that case, just change the base branch for the PR, as described above.

2017-10-30 17:12 UTC, crayolakat commented
Okay, I've changed the base.

2017-10-30 18:15 UTC, bibekg commented
Just took a look at it in-browser. Looks great! Only thing I'd suggest changing up is reducing the upper/lower margin on the text and adding a little bit of padding on the sides.
![image](https://user-images.githubusercontent.com/8083680/32187945-a5e16cb6-bd63-11e7-969c-81ef378dbf35.png)

2017-11-01 13:03 UTC, crayolakat commented
I added padding to the sides and increased the line height to reduce the upper/lower margins. I think the upper/lower margins still look a bit too big, do you think I should increase the text size or crop the picture?

2017-11-01 15:10 UTC, bibekg commented
I think you should decrease the text size a little bit (maybe to `$text_sm` or `$text_md`) and then reduce your `$program_footer_height` SCSS variable to about 500px.

2017-11-05 02:55 UTC, crayolakat commented
Made the changes, what do you think now?

2017-11-05 03:47 UTC, crayolakat commented
I also added a few things to the code to make it compatible with Internet Explorer.

2017-11-09 05:29 UTC, bibekg requested changes
Left a comment on a the polyfill. Also, I'd like to suggest a few other changes:
1. Move the ProgramFooter component from `components` to `pages/OurProgramsPage/ProgramViews` since it's not really going to be used anywhere besides ProgramViews.
2. Same thing goes for the `views/VirutalClassroom` component. It should just be located within `pages/OurProgramsPage/VirtualClassroomsView`
3. I noticed there are two instances of the footer image in this pull request as both `footer.jpg` and `virtual-learning.jpg`. Delete one and resize the other so it has a width of ~1000px in order to reduce file size/page load time.

2017-11-09 05:29 UTC, bibekg commented on src/views/Navbar/NavbarDropdown/NavbarDropdown.js
> +  //Polyfill for Array.prototype.find (method is not compatible with Internet Explorer)
Nice, great work finding the IE bug!

Only comment here is, polyfills should be not be placed within a React component. A good idea would be to move it to `src/utilities/polyfill.js`, then just throw in a 
```js
import './utilities/polyfill'
```
at the top of `src/index.js`

2017-11-09 21:29 UTC, crayolakat commented
I made the changes and fixed another IE bug that I noticed. I actually noticed a lot of IE bugs, but have not had the time to fix. Do you want me to start logging them somewhere?

2017-11-12 19:21 UTC, bibekg commented
That would be great. Just file them as issues here on the Github.

2017-11-12 19:21 UTC, bibekg approved these changes

2017-11-12 19:23 UTC, bibekg commented
Good work. 👍 I've assigned the Learning Disabilities program view to you to work on next.

2017-11-12 23:21 UTC, merged