Is 65
the-coding-school/the-cs pull request #77
Opened 2017-12-13 12:33 UTC by zacharysang

#65: Still needs some work for mobile-friendliness, but wanted to get some feedback on current progress.

Notes:
* Some of the svg files were missing from the bottom 3 icons, so I used what was available and appropriate
* I changed the 'Problems & How We Approach Them' part to make it a lot easier to code (I changed the pointed sides to just make it a rectangle. I can put more time into making this match the mockup, but felt it may require more time than it's worth

Let me know what you think!

2017-12-14 20:23 UTC, bibekg commented
I just changed the base to `programs-page-redesign` since that's what we're gonna put all these Program Views into before merging to master

2017-12-14 20:36 UTC, bibekg commented
A few notes:

1. Leave the bar with the text "codeConnects" out of the CodeConnectsView component. Instead we'll put that bar in the OurProgramsPage component and make it dynamic so that it shows the text for whichever view the user is on at the time.
2. I'm seeing a lot of ESLint warnings about variables that are defined but unused. Make sure you clean those errors up.
3. The image behind the text "Through year-long instruction..." is showing up letterboxed with gray bars on the sides. Try using `object-fit: cover` on the image element.

2017-12-15 05:22 UTC, zacharysang commented
@bibekg this commit fixes your discussed issues and also improve the mobile support for this view

2017-12-17 05:11 UTC, bibekg commented
I think we should also pull out the subtitle bar that says "A diverse approach..." as well since we should include that as part of the OurProgramsPage component as well.

![image](https://user-images.githubusercontent.com/8083680/34076726-8f33a860-e2a4-11e7-8d4d-6aa8f4bb12fa.png)

Also, this "Problems"/"How We Approach Them" double header is a little bit confusing as a reader. I think it should just be a top header with a larger font size that says "Our Approach" and below it, paragraph-sized text saying something like "The traditional educational model has three key problems that we strive to fix."

What do you think?

2017-12-17 05:20 UTC, zacharysang commented
Yeah, I think that reads a little more nicely. Doesn't make the reader connect the dots quite as much. Should I go ahead and put it in with my removal of that subheading?

2017-12-17 22:07 UTC, bibekg commented
Looks good. Only comment I have now is that the font size hierarchy doesn't make sense. I think "Our Approach" should be larger and the subtitle text should be a little smaller.

2017-12-18 02:01 UTC, zacharysang commented
@bibekg I think that the the 'Our Approach' heading should be bigger, but am worried if we make the subheading smaller, it'll look too small.

Here's an image of what is looks like with just the heading upped from $text_md --> $text_lg:

![screenshot 2017-12-18 at 10 00 26](https://user-images.githubusercontent.com/17336621/34086871-58c8f208-e3da-11e7-9dc1-25a1e3d3ae5e.png)

2017-12-19 00:22 UTC, bibekg commented
I think that's good.

2017-12-19 00:23 UTC, bibekg requested changes
I'm noticing a lot of odd stylistic issues like odd indentation and empty lines. Do you happen to have ESLint configured for your text editor?

2017-12-19 00:23 UTC, bibekg commented on src/components/ProgramApproachPiece/ProgramApproachPiece.js
> +		        icon,
Spacing

2017-12-19 00:23 UTC, bibekg commented on src/components/ProgramApproachPiece/ProgramApproachPiece.js
> +
Unnecessary empty lines.

2017-12-19 00:43 UTC, zacharysang commented
I don't think I do. I'll see if I can't get that going. What linting style does this project use?

2017-12-19 02:16 UTC, bibekg approved these changes

2017-12-19 02:16 UTC, bibekg commented
Gonna approve for now despite the linting issues since we'll get those resolved later in a PR off of `master`.

2017-12-19 02:30 UTC, merged